name: Publish npm package

on:
  push:
    branches:
      - main
      - fix/memory

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Compile artifacts
        run: npm run artifacts

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/fix/memory" ]; then
            npm publish --tag beta
          else
            npm publish
          fi
